### PR TITLE
Added Spanish word list file (es_ES)

### PR DESCRIPTION
**Pull request by mirkoooo**
Added the 1000 most common words in Iberian Spanish file (es_ES.txt), from [Real Academia Española de la Lengua](http://corpus.rae.es/lfrecuencias.html). Anyone pls add it to the code.

### CODE REVIEW

**Comment by peregrinogris** [comment]
That list just has the 1000 most used words, but doesn't include their conjugations nor inflections.

**Comment by peregrinogris** [comment]
Nevermind, the list has some of those, compiling this lists is hard and I'm not a linguist ;)
On the other hand, the English file is not just 1000LOC, is around 3500LOC. That's because I assume it has the different forms and conjugations of the 1000 most common words.

**Comment by mortenjust** [comment]
Yes, exactly. A nice thing to do would be to use NSLinguisticTagger to find the root form of the word, and then look up the word in the list

**Comment by mortenjust** [comment]
If you do come across a list with all conjugations that would work until we get the tagger up and running. Thanks for adding this!

**Pull request closed without merging**
