### PR TITLE
XKCD Simple Writer Word List 0.1.4

### PR DESCRIPTION
**Pull request by tlk**
Sync with https://xkcd.com/simplewriter/words.js ;-)

### CODE REVIEW

**Comment by mortenjust** [comment]
Thanks! Just so I understand - 1. what is the difference between the two lists exactly? 2. Seems the new list contains 3,635 words and not the 1,000 that was the initial premise?

**Comment by mortenjust** [comment]
3k words would surely be easier to write with than just the 1k. Maybe this is a preference; easy, medium, hard

**Comment by mortenjust** [comment]
Or, easy, medium, hard, star wars, harry potter, etc.

**Comment by tlk** [comment]
This diff of the two sorted wordlists is more readable: https://github.com/tlk/cleartext-mac/commit/9bdd62816bf130aa9da3068ac9bfce23007fd37a.patch (from https://github.com/tlk/cleartext-mac/tree/xkcd-wordlist)

For instance, "x", "y" and "z" are removed and "accept", "accepted", "accepting" and "accepts" are added.

Out of curiosity: what is the initial source of simplewords.txt?

**Comment by mortenjust** [comment]
Okay, added your list. However, messed up in the order of things and you lost your direct attribution to the file. Feel free to submit a new PR if you want your name on it :)

The original list is from Google's trillion word corpus

**Comment by tlk** [comment]
:+1: no worries :-)

**Pull request merged**
