### PR TITLE
Add Dutch language list

### PR DESCRIPTION
**Pull request by Haroenv**
source: https://nl.wiktionary.org/wiki/WikiWoordenboek:Lijst_met_1000_basiswoorden

I've noted however that it's about base words, and verbs aren't conjugated.

### CODE REVIEW

**Comment by Zegnat** [comment]
Any idea what Wiktionary’s source for this list is? It does not seem like a frequency list at all. All they say is that it is based on [a list from the Simple English Wikipedia](https://simple.wikipedia.org/wiki/Wikipedia_talk:List_of_1000_basic_words). That list has [its problems](https://simple.wikipedia.org/wiki/Wikipedia_talk:List_of_1000_basic_words#Missing_words.3F) too, like not listing the word “two” and not citing a source.

In fact, the Dutch list might just be a straight-up translation of the English one. It seems to list “tweede” and not “twee”, just like the English one. Making me doubt its correctness as a list of most used words even more.

Apparently [there are corpora available for frequency analytics](https://onzetaal.nl/taaladvies/advies/woordfrequentie) (<i>Genootschap Onze Taal</i>, Dutch), but I was unable to find an actual list.

**Comment by Haroenv** [comment]
You're right that this isn't a good list. 

The Corpus Nederlandse taal is available for free<sup>*</sup> here: http://tst-centrale.org/nl/producten/corpora/corpus-gesproken-nederlands/6-17

*: €100 for the hard disk you get it on

**Comment by Haroenv** [comment]
I've requested the language list from e-Lex and received them here: https://github.com/Haroenv/frequentielijsten-corpus From this the most used words can be picked.

**Comment by Zegnat** [comment]
That’s really interesting, thanks for that @Haroenv! I probably wont have time to look at it closely ’til the upcoming weekend, but you can count on me checking out the different lists :smile:

**Comment by Haroenv** [comment]
I'll be compiling a list myself from the source I linked

**Pull request closed without merging**
