### PR TITLE
Add missing trump image

### PR DESCRIPTION
**Pull request by ejensen**
trumpBackground.png is referenced in the storyboard, but is not found in the repository.

### CODE REVIEW

**Comment by mortenjust** [comment]
Hm, weird. It works as expected here. Are you on the latest master branch? 

The intended behavior is to show this image if language "Trump" is selected, and hide it if any other language is selected.

**Comment by ejensen** [comment]
The only image commited in the asset catalog is the app icon: https://github.com/mortenjust/cleartext-mac/tree/master/Simpler/Assets.xcassets

You likely have the image on your computer. So it's displaying for you. But it appears to have never been committed to the git repro. You can verify this by cloning the master branch to a different directory, then running the app.

**Comment by ejensen** [comment]
Performing a search in the repository shows that the image name is referenced in the storyboard, but the image is not included in the repository https://github.com/mortenjust/cleartext-mac/search?q=trumpBackground

**Comment by mortenjust** [comment]
Thanks!

**Pull request merged**
